# Global settings applied to the whole site.  
# 
# “base” is directory to change to before starting build
# “publish” is the directory to publish (relative to root of your repo)
# “command” is your build command

[build]
  base    = ""
  publish = "dist"
  command = "npm run-script build"